import type { ComponentType } from 'react';
import type { PanelType } from '../lib/panels';
import { CorrelationPanel, SeasonalityPanel } from './analytics';
import { CryptoLive, OrderBook } from './crypto';
import { FxPanel, IdxMovers, MarketHours } from './indonesia';
import { MacroPanel, YieldCurvePanel } from './macro';
import { ChartPanel, MarketOverview, Watchlist } from './markets';
import { NewsPanel } from './news';
import { PulsePanel } from './pulse';
import { AskPanel, Calculators, GuidePanel } from './tools';
import { AssetHubPanel, BondsPanel, GlobalMarketsPanel, FundPanel, ScreenerPanel, SbnPanel, UsMarketsPanel } from './expanded';
import { CompanyFundamentalsPanel, EquityFactorPanel, EquityPricesPanel, IdxAuctionFlowPanel, IdxForeignFlowPanel, IdxOwnershipPanel, IdxStockScannerPanel, InstitutionalPortfoliosPanel, InvestorPortfoliosPanel, MarketBreadthPanel, StockScreenerPanel, SectorRotationPanel, EtfDetailPanel, EtfFlowsPanel, EtfPricesPanel, EtfScreenerPanel, DollarFundingStressPanel, FxCarryPanel, FxStrengthPanel, ForexPricesPanel, FixedIncomePricesPanel, GlobalYieldCurvePanel, UsRatePricingPanel, UsRealYieldsPanel, CreditDefaultSwapPanel, CreditSentimentPanel, CreditRatingsPanel, AgricultureWeatherPanel, CommodityPricesPanel, CrudeOilFundamentalPanel, GoldFundamentalPanel, GoldIntermarketPanel, CryptoScannerPanel, CryptoNarrativesPanel, CryptoWhalePanel, CryptoPricesPanel, LiquidationMapPanel, FuturesTermStructurePanel, MarketVolatilityPanel, OptionsAnalyticsPanel, AssetsRatioPanel, MarketCompositeSentimentPanel, MarketFlowPanel, MarketRegimePanel, CotReportPanel, CtaPositioningPanel, DumbMoneyPanel, OrderFlowPanel, LiquidityStructurePanel, CentralBankDataPanel, EconomicGrowthPanel, EmploymentDataPanel, FedLiquidityPanel, FiscalDataPanel, InflationDataPanel, MacroCountryPanel, MacroAgentPanel, MacroRegimePanel, RecessionProbabilityPanel, GeopoliticalPanel, GlobalTradePanel, PortActivityPanel, StreamingChannelsPanel, AnalystReportsPanel, EconomicCalendarPanel, InstitutionalResearchPanel, MarketResearchAgentPanel, MorningBriefsPanel, NewsSummaryPanel, SessionSummaryPanel } from './research';
import type { PanelProps } from './types';

/** Panel type → component. Metadata (titles, sizes, keywords) lives in lib/panels.ts. */
export const PANEL_COMPONENTS: Record<PanelType, ComponentType<PanelProps>> = {
  OVR: MarketOverview,
  PLS: PulsePanel,
  IDX: IdxMovers,
  CHT: ChartPanel,
  WL: Watchlist,
  NWS: NewsPanel,
  FX: FxPanel,
  YC: YieldCurvePanel,
  MAC: MacroPanel,
  CRY: CryptoLive,
  BOOK: OrderBook,
  CAL: Calculators,
  CLK: MarketHours,
  COR: CorrelationPanel,
  SEA: SeasonalityPanel,
  ASK: AskPanel,
  HELP: GuidePanel,
  USA: UsMarketsPanel,
  GLO: GlobalMarketsPanel,
  BND: BondsPanel,
  SBN: SbnPanel,
  FND: FundPanel,
  SCR: ScreenerPanel,
  HUB: AssetHubPanel,
  CFD: CompanyFundamentalsPanel,
  EFS: EquityFactorPanel,
  EQP: EquityPricesPanel,
  IAF: IdxAuctionFlowPanel,
  IFF: IdxForeignFlowPanel,
  IOW: IdxOwnershipPanel,
  ISS: IdxStockScannerPanel,
  IPP: InstitutionalPortfoliosPanel,
  IVP: InvestorPortfoliosPanel,
  BRD: MarketBreadthPanel,
  STK: StockScreenerPanel,
  ROT: SectorRotationPanel,
  ETD: EtfDetailPanel,
  ETF: EtfFlowsPanel,
  ETP: EtfPricesPanel,
  ETS: EtfScreenerPanel,
  DFS: DollarFundingStressPanel,
  FCA: FxCarryPanel,
  FXS: FxStrengthPanel,
  FXP: ForexPricesPanel,
  FIP: FixedIncomePricesPanel,
  GYC: GlobalYieldCurvePanel,
  URP: UsRatePricingPanel,
  URY: UsRealYieldsPanel,
  CDS: CreditDefaultSwapPanel,
  CMS: CreditSentimentPanel,
  CRR: CreditRatingsPanel,
  AGW: AgricultureWeatherPanel,
  CMD: CommodityPricesPanel,
  OIL: CrudeOilFundamentalPanel,
  GLF: GoldFundamentalPanel,
  GIS: GoldIntermarketPanel,
  CLS: CryptoScannerPanel,
  CNT: CryptoNarrativesPanel,
  CWT: CryptoWhalePanel,
  CPR: CryptoPricesPanel,
  LQM: LiquidationMapPanel,
  FTS: FuturesTermStructurePanel,
  VOL: MarketVolatilityPanel,
  OPT: OptionsAnalyticsPanel,
  ARR: AssetsRatioPanel,
  MCS: MarketCompositeSentimentPanel,
  MFL: MarketFlowPanel,
  MRL: MarketRegimePanel,
  COT: CotReportPanel,
  CTA: CtaPositioningPanel,
  DMI: DumbMoneyPanel,
  OFL: OrderFlowPanel,
  LST: LiquidityStructurePanel,
  CBD: CentralBankDataPanel,
  EGW: EconomicGrowthPanel,
  EMP: EmploymentDataPanel,
  FNL: FedLiquidityPanel,
  FIS: FiscalDataPanel,
  INF: InflationDataPanel,
  MCY: MacroCountryPanel,
  MGA: MacroAgentPanel,
  MGR: MacroRegimePanel,
  REC: RecessionProbabilityPanel,
  GPI: GeopoliticalPanel,
  GTM: GlobalTradePanel,
  POR: PortActivityPanel,
  STR: StreamingChannelsPanel,
  ANR: AnalystReportsPanel,
  ECO: EconomicCalendarPanel,
  INR: InstitutionalResearchPanel,
  MRA: MarketResearchAgentPanel,
  MOR: MorningBriefsPanel,
  NSM: NewsSummaryPanel,
  SES: SessionSummaryPanel,
};
